# Generated by Django 5.2.6 on 2025-10-07 08:06

import apps.patients.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_patient', models.CharField(blank=True, help_text='Format: P{ANNÉE}{MOIS}{NUMÉRO}', max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(blank=True, max_length=200)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('groupe_sanguin', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apps.patients.models.patient_photo_path)),
                ('photo_carte_identite', models.ImageField(blank=True, null=True, upload_to=apps.patients.models.patient_id_card_path)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('telephone_secondaire', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.TextField(blank=True)),
                ('quartier_commune', models.CharField(blank=True, max_length=100)),
                ('ville', models.CharField(blank=True, default='Kinshasa', max_length=100)),
                ('contact_urgence_nom', models.CharField(blank=True, max_length=100)),
                ('contact_urgence_lien', models.CharField(blank=True, choices=[('parent', 'Parent'), ('conjoint', 'Conjoint(e)'), ('enfant', 'Enfant'), ('ami', 'Ami(e)'), ('autre', 'Autre')], max_length=20)),
                ('contact_urgence_telephone', models.CharField(blank=True, max_length=20)),
                ('allergies', models.TextField(blank=True, help_text='Allergies connues')),
                ('diabete', models.BooleanField(default=False)),
                ('hypertension', models.BooleanField(default=False)),
                ('asthme', models.BooleanField(default=False)),
                ('epilepsie', models.BooleanField(default=False)),
                ('drepanocytose', models.BooleanField(default=False)),
                ('vih', models.BooleanField(default=False)),
                ('autre_maladie_chronique', models.CharField(blank=True, max_length=200)),
                ('traitements_en_cours', models.TextField(blank=True)),
                ('antecedents_chirurgicaux', models.TextField(blank=True)),
                ('antecedents_medicaux', models.TextField(blank=True)),
                ('notes_medicales', models.TextField(blank=True, help_text='Notes importantes')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente', 'En attente de validation'), ('actif', 'Actif'), ('inactif', 'Inactif')], default='brouillon', max_length=20)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_crees', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'db_table': 'patients',
                'ordering': ['-date_creation'],
            },
        ),
    ]
