# Generated by Django 5.2.6 on 2025-10-07 08:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierMedical',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_consultation', models.DateTimeField()),
                ('motif_consultation', models.TextField(help_text='Raison de la visite')),
                ('symptomes', models.TextField(blank=True, help_text='Liste des symptômes observés')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='En °C', max_digits=4, null=True)),
                ('tension_arterielle', models.CharField(blank=True, help_text='Ex: 120/80', max_length=20)),
                ('poids', models.DecimalField(blank=True, decimal_places=2, help_text='En kg', max_digits=5, null=True)),
                ('taille', models.DecimalField(blank=True, decimal_places=2, help_text='En cm', max_digits=5, null=True)),
                ('diagnostic', models.TextField()),
                ('diagnostic_differentiel', models.TextField(blank=True, help_text='Autres diagnostics possibles')),
                ('examens_complementaires', models.TextField(blank=True, help_text='Examens demandés (radio, analyses, etc.)')),
                ('prescription', models.TextField(blank=True, help_text='Médicaments prescrits')),
                ('posologie', models.TextField(blank=True, help_text='Dosage et fréquence')),
                ('notes_medicales', models.TextField(blank=True)),
                ('recommandations', models.TextField(blank=True, help_text='Conseils au patient')),
                ('date_prochain_rdv', models.DateField(blank=True, null=True)),
                ('urgence', models.CharField(choices=[('faible', 'Faible'), ('moyenne', 'Moyenne'), ('elevee', 'Élevée'), ('critique', 'Critique')], default='faible', max_length=20)),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('ferme', 'Fermé'), ('en_attente', 'En attente'), ('archive', 'Archivé')], default='ouvert', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers_crees', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Dossier médical',
                'verbose_name_plural': 'Dossiers médicaux',
                'db_table': 'dossiers_medicaux',
                'ordering': ['-date_consultation'],
            },
        ),
    ]
