# Generated by Django 5.2.6 on 2025-10-07 08:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyseStatistique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_analyse', models.CharField(choices=[('age_groups', "Analyse par tranche d'âge"), ('pathologies', 'Pathologies fréquentes'), ('geographic', 'Répartition géographique'), ('annual_report', 'Rapport annuel'), ('gender_analysis', 'Analyse par sexe')], max_length=50)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('parametres', models.JSONField(default=dict, help_text="Paramètres de l'analyse")),
                ('resultats', models.JSONField(default=dict, help_text="Résultats de l'analyse")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=True, help_text='Visible par tous les analystes')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses_creees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analyse statistique',
                'verbose_name_plural': 'Analyses statistiques',
                'db_table': 'analyses_statistiques',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='RapportAnnuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField()),
                ('total_patients', models.PositiveIntegerField()),
                ('total_consultations', models.PositiveIntegerField()),
                ('pathologies_principales', models.JSONField(default=list)),
                ('statistiques_age', models.JSONField(default=dict)),
                ('statistiques_sexe', models.JSONField(default=dict)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rapport annuel',
                'verbose_name_plural': 'Rapports annuels',
                'db_table': 'rapports_annuels',
                'unique_together': {('annee',)},
            },
        ),
    ]
